import swaggerJsdoc from 'swagger-jsdoc';

const options: swaggerJsdoc.Options = {
  apis: ['./src/swagger/swagger-components.ts', './src/routes/**/*.ts'],
  basePath: '/',
  host: 'localhost:8080',
  swaggerDefinition: {
    components: {},
    info: {
      title: 'Teste api jsdoc generator',
      description: 'Test API with autogenerated swagger doc',
      version: '0.0.1',
    },
  },
};

const specs = swaggerJsdoc(options);

export default specs;
