const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  apis: ['./src/swagger/swagger-components.js', './src/routes/**/*.js'],
  basePath: '/',
  host: 'localhost:8080',
  swaggerDefinition: {
    components: {},
    info: {
      title: 'Teste api jsdoc generator',
      description: 'Test API with autogenerated swagger doc',
      version: '0.0.1',
      swagger: '2.0',
    },
  },
};

const specs = swaggerJsdoc(options);

module.exports = specs;
